### ISSUE TITLE
Support create multiple services from template Schema

### ISSUE THREAD

**Issue by sangdth** [productdevbookcom/easypanel#13]
Thanks for nice works. 🙏 

I found out we do not have support `templates` route at the moment, it would be great if this SDK also support it:

```
api/trpc/templates.createFromSchema
```

**Comment by sangdth** [comment]
I can try to make a PR if you don't have time, would someone review it? CC: @productdevbook

**Comment by productdevbook** [comment]
of course, I can look at it when I'm off jobs
