### ISSUE TITLE
Merge the input `domains` with default value in `CreateService` interface

### ISSUE THREAD

**Issue by sangdth** [productdevbookcom/easypanel#14]
Currently the `CreateService` interface requires the `domains` property, but in the method it replaces it completely:

```typescript
  async function create(
    serviceType: ServiceType,
    body: CreateService,
  ) {
    body.domains = [
      {
        host: '$(EASYPANEL_DOMAIN)',
      },
    ]
    ...
  }
```
[Source code](https://github.com/Easypanel-Community/easypanel/blob/a5dd5560ec8e2f74f96f0961c2d24b99dac775c8/src/service/services.ts#L29)

so I think it makes sense if we either make it optional or merge it:

Suggest solution:
Merge the body.domains with `EASYPANEL_DOMAIN`:
```typescript
using deepmerge or just simply:
body.domains = [{ host: '$(EASYPANEL_DOMAIN)' }, ...body.domains]
```

What do you think?

**Comment by productdevbook** [comment]
@deiucanta is support ?
